#!/usr/bin/env bash
# BareZen-Drive one-command installer.
#
# Deploys the server (with the Web client built in) as Docker containers.
# The Web client is served by the server itself, so "web only" does not exist:
# pick "server" (everything) and open http://<host>:<port> for the Web client,
# or install the Android APK on a phone and point it at the same address.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/linanwanttodo/BareZen-Drive/master/install.sh | bash
#   bash install.sh --dir /opt/barezen --port 8080 --version latest
#
# The script asks for the required values, writes .env, then starts the stack.
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/linanwanttodo/BareZen-Drive/master"
INSTALL_DIR="/opt/barezen"
SERVER_PORT="8080"
IMAGE_TAG="latest"

log() { printf '\n\033[1;32m==>\033[0m %s\n' "$*"; }
err() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --dir) INSTALL_DIR="$2"; shift 2 ;;
    --port) SERVER_PORT="$2"; shift 2 ;;
    --version) IMAGE_TAG="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,12p' "$0"; exit 0 ;;
    *) err "unknown option: $1 (see --help)" ;;
  esac
done

command -v docker >/dev/null 2>&1 || err "Docker is required: https://docs.docker.com/engine/install/"
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  err "Docker Compose is required (docker compose plugin or docker-compose)."
fi

log "Welcome to BareZen-Drive (self-hosted personal cloud drive)"
echo "This deploys: PostgreSQL 16 + the BareZen-Drive server (Web client included)."
echo "After it starts: open http://<this-host>:${SERVER_PORT} for the Web client,"
echo "and/or install the Android APK from GitHub Releases pointing at the same address."
echo

# ---- interactive env wizard (skipped for values already given) ----
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

[ -f .env ] && { log ".env already exists at $INSTALL_DIR/.env - keeping it"; } || {
  log "Generating .env in $INSTALL_DIR"
  read -r -p "Port to expose the server on [${SERVER_PORT}]: " input_port
  [ -n "${input_port:-}" ] && SERVER_PORT="$input_port"

  read -r -s -p "Database password (POSTGRES_PASSWORD, blank = generate): " input_dbpass; echo
  [ -n "${input_dbpass:-}" ] || input_dbpass="$(head -c 24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)"

  read -r -s -p "JWT secret (JWT_SECRET, blank = generate): " input_jwt; echo
  [ -n "${input_jwt:-}" ] || input_jwt="$(head -c 48 /dev/urandom | base64)"

  cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
JWT_SECRET=${input_jwt}
POSTGRES_DB=barezen
POSTGRES_USER=barezen
POSTGRES_PASSWORD=${input_dbpass}
SERVER_PORT=${SERVER_PORT}
EOF
  chmod 600 .env
}

log "Fetching docker-compose.yml (image: ghcr.io/linanwanttodo/barezen-drive:${IMAGE_TAG})"
curl -fsSL -o docker-compose.yml "${REPO_RAW}/docker-compose.yml"
# Pin the image tag the user chose (default latest).
sed -i.bak "s#ghcr.io/linanwanttodo/barezen-drive:latest#ghcr.io/linanwanttodo/barezen-drive:${IMAGE_TAG}#" docker-compose.yml && rm -f docker-compose.yml.bak

# The container runs as uid 10001; a bind-mounted host directory owned by the
# installing user would deny it write access (AccessDeniedException on startup).
# World-writable on this one data directory is the no-sudo deployment path.
mkdir -p data/storage
chmod 777 data/storage

log "Pulling images"
$COMPOSE pull --quiet || true

log "Starting the stack"
$COMPOSE up -d

log "Waiting for the server to become healthy"
for i in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${SERVER_PORT}/health" >/dev/null 2>&1; then
    echo
    echo "  BareZen-Drive is up:  http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo localhost):${SERVER_PORT}"
    echo "  Config directory:     $INSTALL_DIR"
    echo "  Data directory:       $INSTALL_DIR/data/storage (files) and the pgdata volume (metadata)"
    echo
    echo "  First step: open the address above, register your account,"
    echo "  then close open registration in Settings -> Server."
    echo
    echo "  Commands: cd $INSTALL_DIR && $COMPOSE pull && $COMPOSE up -d   (upgrade)"
    echo "            cd $INSTALL_DIR && $COMPOSE logs -f server           (logs)"
    exit 0
  fi
  sleep 2
done

echo
$COMPOSE logs --tail 40 server
err "the server did not answer on port ${SERVER_PORT} within 120s - see the logs above"
