package com.linan.barezen_drive.files

import com.linan.barezen_drive.db.DatabaseFactory
import com.linan.barezen_drive.db.FilesTable
import com.linan.barezen_drive.storage.StorageProvider
import com.linan.barezen_drive.storage.thumbKey
import io.ktor.utils.io.ByteReadChannel
import io.ktor.utils.io.jvm.javaio.toInputStream
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import org.jetbrains.exposed.sql.and
import org.jetbrains.exposed.sql.transactions.transaction
import org.jetbrains.exposed.sql.update
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import java.io.ByteArrayOutputStream
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.CompletableFuture
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.TimeUnit
import javax.imageio.ImageIO
import javax.imageio.ImageReadParam
import javax.imageio.ImageReader
import kotlin.io.path.deleteIfExists
import kotlin.math.ceil
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt

/**
 * Server-side thumbnail fallback. Covers are normally generated by the client
 * before upload; when a file has no stored cover yet (old uploads, desktop
 * clients without a generator, or a failed cover PUT), this service decodes
 * the stored blob once and stores a content-addressed JPEG so every viewer of
 * the same bytes benefits.
 *
 * ffmpeg (image + video frames) is preferred; for images a pure-Java ImageIO
 * fallback keeps generation working on hosts without ffmpeg. Everything is
 * best-effort: an undecodable file simply keeps "no thumbnail" and the API
 * still answers 404.
 */
object ThumbnailService {
    private const val MAX_EDGE = 512

    /**
     * Ceiling for a stored cover, in bytes. One definition, used by the
     * generator below *and* by the PUT route that accepts a client-made cover:
     * two copies of this number meant the server could start publishing covers
     * its own PUT endpoint would have rejected, and nobody would notice until a
     * client sent a large one.
     */
    const val MAX_THUMB_BYTES = 512 * 1024

    private const val IMAGE_SOURCE_MAX_BYTES = 100L * 1024 * 1024
    private const val VIDEO_SOURCE_MAX_BYTES = 500L * 1024 * 1024
    private const val FFMPEG_TIMEOUT_SECONDS = 60L
    // Decompression-bomb guard: pixels allowed to materialize during ImageIO
    // fallback decoding (the container heap is small).
    private const val MAX_SOURCE_PIXELS = 64L * 1024 * 1024

    private enum class MediaKind { IMAGE, VIDEO, NONE }

    /** Probed once; true when the ffmpeg binary is usable on this host. */
    @Volatile
    private var ffmpegOk: Boolean? = null

    /** One generation per content hash: concurrent GETs wait instead of each
     *  spawning their own ffmpeg/decoder (bounded CPU + disk usage). */
    private val inFlight = ConcurrentHashMap<String, CompletableFuture<Boolean>>()

    /** Dedicated bounded pool for generation work: supplyAsync's default
     *  ForkJoinPool.commonPool() shares CPU-1 blocking-sensitive threads with
     *  parallel streams and any other commonPool user, and generation blocks
     *  on ffmpeg/decoders. Two workers cap CPU and disk pressure on small
     *  hosts; inFlight already collapses same-content requests. Daemon
     *  threads, so the pool never blocks JVM shutdown. */
    private val genPool = java.util.concurrent.Executors.newFixedThreadPool(2) { r ->
        Thread(r, "thumb-gen").apply { isDaemon = true }
    }

    fun ffmpegAvailable(): Boolean {
        ffmpegOk?.let { return it }
        val ok = runCatching {
            val p = ProcessBuilder("ffmpeg", "-version")
                .redirectError(ProcessBuilder.Redirect.DISCARD)
                .redirectOutput(ProcessBuilder.Redirect.DISCARD)
                .start()
            val finished = p.waitFor(5, TimeUnit.SECONDS)
            if (!finished) {
                p.destroyForcibly()
                p.waitFor(5, TimeUnit.SECONDS)
            }
            finished && p.exitValue() == 0
        }.getOrDefault(false)
        ffmpegOk = ok
        return ok
    }

    /**
     * Makes sure a thumbnail exists for [meta]'s content: returns true when a
     * cover is stored (existing or freshly generated) and the flag is set.
     * Concurrent calls for the same content share one generation.
     */
    suspend fun ensureThumbnail(storage: StorageProvider, meta: FileMeta): Boolean = withContext(Dispatchers.IO) {
        val key = thumbKey(meta.sha256)
        if (storage.exists(key)) {
            flagThumbnails(meta)
            return@withContext true
        }
        // Get-or-create one shared future per thumb key: concurrent requests
        // await the winner's result instead of duplicating the decode work.
        // (computeIfAbsent must store the REAL future - storing a completed
        // placeholder would hand late callers an instant false.)
        val future = inFlight.computeIfAbsent(key) {
            val f = CompletableFuture.supplyAsync<Boolean>({ generateAndStore(storage, meta, key) }, genPool)
            f.whenComplete { _, _ -> inFlight.remove(key, f) }
            f
        }
        runCatching { future.get(FFMPEG_TIMEOUT_SECONDS + 30, TimeUnit.SECONDS) }.getOrDefault(false)
    }

    /** Blocking generation; runs on the CompletableFuture fork-join worker. */
    private fun generateAndStore(storage: StorageProvider, meta: FileMeta, key: String): Boolean {
        // Re-check: another request may have finished while this one queued up.
        if (runBlockingIo { storage.exists(key) }) {
            flagThumbnails(meta)
            return true
        }
        val bytes = generate(storage, meta) ?: return false
        if (bytes.isEmpty() || bytes.size > MAX_THUMB_BYTES) return false
        val stored = runCatching { runBlockingIo { storage.put(key, ByteReadChannel(bytes)) } }.getOrNull() != null
        if (stored) flagThumbnails(meta)
        return stored
    }

    private fun generate(storage: StorageProvider, meta: FileMeta): ByteArray? {
        val kind = mediaKind(meta.mimeType, meta.name)
        if (kind == MediaKind.NONE) return null
        val limit = if (kind == MediaKind.VIDEO) VIDEO_SOURCE_MAX_BYTES else IMAGE_SOURCE_MAX_BYTES
        if (meta.size !in 1..limit) return null

        // Prefer the stored blob in place; when storage is not local, stream it
        // once to a temp file so the decoder gets a real seekable file.
        val (source, temp) = materializeSource(storage, meta)
        try {
            return when {
                ffmpegAvailable() -> ffmpegFrame(source) ?: if (kind == MediaKind.IMAGE) imageIoCover(source) else null
                kind == MediaKind.IMAGE -> imageIoCover(source)
                else -> null
            }
        } finally {
            temp?.deleteIfExists()
        }
    }

    private fun materializeSource(storage: StorageProvider, meta: FileMeta): Pair<Path, Path?> {
        storage.resolvePath(meta.storageKey)?.let { return it to null }
        val tmp = Files.createTempFile("thumb-src-", ".bin")
        runCatching {
            val ch = runBlockingIo { storage.get(meta.storageKey) }
            ch.toInputStream().use { ins ->
                Files.copy(ins, tmp, java.nio.file.StandardCopyOption.REPLACE_EXISTING)
            }
        }.onFailure {
            tmp.deleteIfExists()
            throw it
        }
        return tmp to tmp
    }

    /** Extracts one frame scaled to fit within 512x512 into a temp JPEG. */
    private fun ffmpegFrame(source: Path): ByteArray? {
        val out = Files.createTempFile("thumb-", ".jpg")
        return try {
            val cmd = listOf(
                "ffmpeg", "-y", "-nostdin", "-loglevel", "error", "-ss", "0",
                "-i", source.toString(),
                "-frames:v", "1",
                "-vf", "scale=w=$MAX_EDGE:h=$MAX_EDGE:force_original_aspect_ratio=decrease",
                "-q:v", "4",
                "-f", "image2",
                out.toString(),
            )
            val proc = ProcessBuilder(cmd)
                .redirectError(ProcessBuilder.Redirect.DISCARD)
                .redirectOutput(ProcessBuilder.Redirect.DISCARD)
                .start()
            val finished = proc.waitFor(FFMPEG_TIMEOUT_SECONDS, TimeUnit.SECONDS)
            if (!finished) {
                proc.destroyForcibly()
                proc.waitFor(5, TimeUnit.SECONDS)
            }
            if (finished && proc.exitValue() == 0 && Files.size(out) > 0) Files.readAllBytes(out) else null
        } catch (_: java.io.IOException) {
            null
        } catch (_: InterruptedException) {
            Thread.currentThread().interrupt()
            null
        } finally {
            out.deleteIfExists()
        }
    }

    /**
     * Source-decimation factors for a cover of [targetEdge] px.
     *
     * The point is heap, not speed: a full decode of a 24MP photo materialises
     * ~96MB and a 64MP one ~256MB, which is the entire default heap on a 1G
     * host. Decoding every Nth pixel instead costs a fraction of that and still
     * leaves more pixels than the 512px cover needs, so quality is unchanged
     * after the downscale.
     *
     * Both axes get the same factor (decimating them differently would distort
     * the photo) and it is a power of two, because readers are only obliged to
     * honour powers of two. Capped at 16: past that the cover would be an
     * upscale of a thumbnail and the source guard already refuses anything
     * larger anyway.
     */
    internal fun subsamplingFor(width: Long, height: Long, targetEdge: Int): Pair<Int, Int> {
        if (width <= 0 || height <= 0 || targetEdge <= 0) return 1 to 1
        val longEdge = max(width, height)
        if (longEdge <= targetEdge) return 1 to 1
        // Largest power of two that still leaves at least targetEdge pixels.
        var factor = 1
        while (factor < 16 && ceil(longEdge.toDouble() / (factor * 2)) >= targetEdge) factor *= 2
        return factor to factor
    }

    /**
     * Decodes the source through [subsamplingFor] and nothing else: bounds and
     * decimation factors come from one pass over the header, and the reader
     * then decodes the subsampled grid directly, so the full raster is never
     * materialised.
     */
    private fun decodeSource(reader: ImageReader): BufferedImage? {
        val w = reader.getWidth(0).toLong()
        val h = reader.getHeight(0).toLong()
        // Refuse a decompression bomb before decoding any pixels.
        if (w <= 0 || h <= 0 || w * h > MAX_SOURCE_PIXELS) return null
        val (fx, fy) = subsamplingFor(w, h, MAX_EDGE)
        // A default read param with no cache: the decimation below is the
        // only transformation, and a null param would mean a full decode.
        val param: ImageReadParam = reader.defaultReadParam
            ?: throw javax.imageio.IIOException("reader without a read param")
        if (fx > 1 || fy > 1) param.setSourceSubsampling(fx, fy, 0, 0)
        return reader.read(0, param)
    }

    /**
     * Pure-Java image fallback: decode, downscale to fit 512x512, re-encode JPEG
     * - through one open, one reader, one close.
     *
     * Every exit goes through the same finally, including "no reader for this
     * format" - the exit the previous shape missed, which leaked a file
     * descriptor on every request for a file ImageIO cannot decode (a phone's
     * HEIC, a WEBP the JVM has no plugin for). The same reader then decodes;
     * opening the file a second time to do it would be a second full read of
     * the source for nothing.
     */
    private fun imageIoCover(source: Path): ByteArray? = try {
        ImageIO.setUseCache(false)
        val input = ImageIO.createImageInputStream(source.toFile()) ?: return null
        var reader: ImageReader? = null
        try {
            val readers = ImageIO.getImageReaders(input)
            if (!readers.hasNext()) return null
            reader = readers.next()
            reader.input = input
            val img = decodeSource(reader) ?: return null
            if (img.width <= 0 || img.height <= 0) null else {
                val scale = min(1f, MAX_EDGE.toFloat() / max(img.width, img.height))
                val w = max(1, (img.width * scale).roundToInt())
                val h = max(1, (img.height * scale).roundToInt())
                val canvas = BufferedImage(w, h, BufferedImage.TYPE_INT_RGB)
                val g = canvas.createGraphics()
                g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR)
                g.drawImage(img, 0, 0, w, h, null)
                g.dispose()
                val bytes = ByteArrayOutputStream()
                if (!ImageIO.write(canvas, "jpg", bytes)) null else bytes.toByteArray()
            }
        } finally {
            // dispose() before close(): a reader holding an input must be told
            // to let go of it first.
            reader?.dispose()
            input.close()
        }
    } catch (_: java.io.IOException) {
        null
    } catch (_: javax.imageio.IIOException) {
        null
    }

    /**
     * Marks every row of this user that holds [meta]'s content as having a
     * cover, so a list tile never asks for a cover that is already stored.
     *
     * The only writer of that flag, for both the generator and the PUT route:
     * two hand-written copies of the same UPDATE are two chances to spell the
     * "same content, maybe another file" condition differently.
     */
    internal fun flagThumbnails(meta: FileMeta) {
        transaction(DatabaseFactory.db) {
            FilesTable.update({ (FilesTable.sha256 eq meta.sha256) and (FilesTable.user eq meta.userId) }) {
                it[hasThumbnail] = true
            }
        }
    }

    private fun mediaKind(mime: String?, name: String): MediaKind {
        val m = mime?.lowercase()
        if (!m.isNullOrBlank()) {
            return when {
                m.startsWith("image/") -> MediaKind.IMAGE
                m.startsWith("video/") -> MediaKind.VIDEO
                else -> MediaKind.NONE
            }
        }
        return when (name.substringAfterLast('.', "").lowercase()) {
            "jpg", "jpeg", "png", "webp", "gif", "bmp" -> MediaKind.IMAGE
            "mp4", "mov", "webm", "m4v", "3gp", "avi", "mkv" -> MediaKind.VIDEO
            else -> MediaKind.NONE
        }
    }

    /** Bridge for the (non-suspend) generation thread onto the suspend storage API. */
    private fun <T> runBlockingIo(block: suspend () -> T): T = runBlocking(Dispatchers.IO) { block() }
}
