package com.linan.barezen_drive.files

import com.linan.barezen_drive.db.DatabaseFactory
import com.linan.barezen_drive.db.FilesTable
import com.linan.barezen_drive.storage.StorageProvider
import com.linan.barezen_drive.storage.thumbKey
import io.ktor.utils.io.ByteReadChannel
import io.ktor.utils.io.jvm.javaio.toInputStream
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import org.jetbrains.exposed.sql.and
import org.jetbrains.exposed.sql.transactions.transaction
import org.jetbrains.exposed.sql.update
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import java.io.ByteArrayOutputStream
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.CompletableFuture
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.TimeUnit
import javax.imageio.ImageIO
import kotlin.io.path.deleteIfExists
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt

/**
 * Server-side thumbnail fallback. Covers are normally generated by the client
 * before upload; when a file has no stored cover yet (old uploads, desktop
 * clients without a generator, or a failed cover PUT), this service decodes
 * the stored blob once and stores a content-addressed JPEG so every viewer of
 * the same bytes benefits.
 *
 * ffmpeg (image + video frames) is preferred; for images a pure-Java ImageIO
 * fallback keeps generation working on hosts without ffmpeg. Everything is
 * best-effort: an undecodable file simply keeps "no thumbnail" and the API
 * still answers 404.
 */
object ThumbnailService {
    private const val MAX_EDGE = 512
    private const val MAX_THUMB_BYTES = 512 * 1024
    private const val IMAGE_SOURCE_MAX_BYTES = 100L * 1024 * 1024
    private const val VIDEO_SOURCE_MAX_BYTES = 500L * 1024 * 1024
    private const val FFMPEG_TIMEOUT_SECONDS = 60L
    // Decompression-bomb guard: pixels allowed to materialize during ImageIO
    // fallback decoding (the container heap is small).
    private const val MAX_SOURCE_PIXELS = 64L * 1024 * 1024

    private enum class MediaKind { IMAGE, VIDEO, NONE }

    /** Probed once; true when the ffmpeg binary is usable on this host. */
    @Volatile
    private var ffmpegOk: Boolean? = null

    /** One generation per content hash: concurrent GETs wait instead of each
     *  spawning their own ffmpeg/decoder (bounded CPU + disk usage). */
    private val inFlight = ConcurrentHashMap<String, CompletableFuture<Boolean>>()

    fun ffmpegAvailable(): Boolean {
        ffmpegOk?.let { return it }
        val ok = runCatching {
            val p = ProcessBuilder("ffmpeg", "-version")
                .redirectError(ProcessBuilder.Redirect.DISCARD)
                .redirectOutput(ProcessBuilder.Redirect.DISCARD)
                .start()
            val finished = p.waitFor(5, TimeUnit.SECONDS)
            if (!finished) {
                p.destroyForcibly()
                p.waitFor(5, TimeUnit.SECONDS)
            }
            finished && p.exitValue() == 0
        }.getOrDefault(false)
        ffmpegOk = ok
        return ok
    }

    /**
     * Makes sure a thumbnail exists for [meta]'s content: returns true when a
     * cover is stored (existing or freshly generated) and the flag is set.
     * Concurrent calls for the same content share one generation.
     */
    suspend fun ensureThumbnail(storage: StorageProvider, meta: FileMeta): Boolean = withContext(Dispatchers.IO) {
        val key = thumbKey(meta.sha256)
        if (storage.exists(key)) {
            flagThumbnails(meta)
            return@withContext true
        }
        // Get-or-create one shared future per thumb key: concurrent requests
        // await the winner's result instead of duplicating the decode work.
        val current = CompletableFuture.completedFuture(false)
        val future = inFlight.putIfAbsent(key, current) ?: run {
            val f = current.thenApplyAsync { generateAndStore(storage, meta, key) }
            f.whenComplete { _, _ -> inFlight.remove(key) }
            f
        }
        runCatching { future.get(FFMPEG_TIMEOUT_SECONDS + 30, TimeUnit.SECONDS) }.getOrDefault(false)
    }

    /** Blocking generation; runs on the CompletableFuture fork-join worker. */
    private fun generateAndStore(storage: StorageProvider, meta: FileMeta, key: String): Boolean {
        // Re-check: another request may have finished while this one queued up.
        if (runBlockingIo { storage.exists(key) }) {
            flagThumbnails(meta)
            return true
        }
        val bytes = generate(storage, meta) ?: return false
        if (bytes.isEmpty() || bytes.size > MAX_THUMB_BYTES) return false
        val stored = runCatching { runBlockingIo { storage.put(key, ByteReadChannel(bytes)) } }.getOrNull() != null
        if (stored) flagThumbnails(meta)
        return stored
    }

    private fun generate(storage: StorageProvider, meta: FileMeta): ByteArray? {
        val kind = mediaKind(meta.mimeType, meta.name)
        if (kind == MediaKind.NONE) return null
        val limit = if (kind == MediaKind.VIDEO) VIDEO_SOURCE_MAX_BYTES else IMAGE_SOURCE_MAX_BYTES
        if (meta.size !in 1..limit) return null

        // Prefer the stored blob in place; when storage is not local, stream it
        // once to a temp file so the decoder gets a real seekable file.
        val (source, temp) = materializeSource(storage, meta)
        try {
            return when {
                ffmpegAvailable() -> ffmpegFrame(source) ?: if (kind == MediaKind.IMAGE) imageIoCover(source) else null
                kind == MediaKind.IMAGE -> imageIoCover(source)
                else -> null
            }
        } finally {
            temp?.deleteIfExists()
        }
    }

    private fun materializeSource(storage: StorageProvider, meta: FileMeta): Pair<Path, Path?> {
        storage.resolvePath(meta.storageKey)?.let { return it to null }
        val tmp = Files.createTempFile("thumb-src-", ".bin")
        runCatching {
            val ch = runBlockingIo { storage.get(meta.storageKey) }
            ch.toInputStream().use { ins ->
                Files.copy(ins, tmp, java.nio.file.StandardCopyOption.REPLACE_EXISTING)
            }
        }.onFailure {
            tmp.deleteIfExists()
            throw it
        }
        return tmp to tmp
    }

    /** Extracts one frame scaled to fit within 512x512 into a temp JPEG. */
    private fun ffmpegFrame(source: Path): ByteArray? {
        val out = Files.createTempFile("thumb-", ".jpg")
        return try {
            val cmd = listOf(
                "ffmpeg", "-y", "-nostdin", "-loglevel", "error", "-ss", "0",
                "-i", source.toString(),
                "-frames:v", "1",
                "-vf", "scale=w=$MAX_EDGE:h=$MAX_EDGE:force_original_aspect_ratio=decrease",
                "-q:v", "4",
                "-f", "image2",
                out.toString(),
            )
            val proc = ProcessBuilder(cmd)
                .redirectError(ProcessBuilder.Redirect.DISCARD)
                .redirectOutput(ProcessBuilder.Redirect.DISCARD)
                .start()
            val finished = proc.waitFor(FFMPEG_TIMEOUT_SECONDS, TimeUnit.SECONDS)
            if (!finished) {
                proc.destroyForcibly()
                proc.waitFor(5, TimeUnit.SECONDS)
            }
            if (finished && proc.exitValue() == 0 && Files.size(out) > 0) Files.readAllBytes(out) else null
        } catch (_: java.io.IOException) {
            null
        } catch (_: InterruptedException) {
            Thread.currentThread().interrupt()
            null
        } finally {
            out.deleteIfExists()
        }
    }

    /** Pure-Java image fallback: decode, downscale to fit 512x512, re-encode JPEG. */
    private fun imageIoCover(source: Path): ByteArray? = try {
        ImageIO.setUseCache(false)
        // Bounds pass first: refuse to materialize a decompression bomb before
        // actually decoding pixels.
        val input = ImageIO.createImageInputStream(source.toFile()) ?: return null
        val readers = ImageIO.getImageReaders(input)
        if (!readers.hasNext()) return null
        val reader = readers.next()
        reader.input = input
        try {
            val w = reader.getWidth(0).toLong()
            val h = reader.getHeight(0).toLong()
            if (w <= 0 || h <= 0 || w * h > MAX_SOURCE_PIXELS) return null
        } finally {
            reader.dispose()
            input.close()
        }
        val img = ImageIO.read(source.toFile()) ?: return null
        if (img.width <= 0 || img.height <= 0) null else {
            val scale = min(1f, MAX_EDGE.toFloat() / max(img.width, img.height))
            val w = max(1, (img.width * scale).roundToInt())
            val h = max(1, (img.height * scale).roundToInt())
            val canvas = BufferedImage(w, h, BufferedImage.TYPE_INT_RGB)
            val g = canvas.createGraphics()
            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR)
            g.drawImage(img, 0, 0, w, h, null)
            g.dispose()
            val bytes = ByteArrayOutputStream()
            if (!ImageIO.write(canvas, "jpg", bytes)) null else bytes.toByteArray()
        }
    } catch (_: java.io.IOException) {
        null
    } catch (_: javax.imageio.IIOException) {
        null
    }

    /** Same-content rows share one cover; flag them all like the PUT route does. */
    private fun flagThumbnails(meta: FileMeta) {
        transaction(DatabaseFactory.db) {
            FilesTable.update({ (FilesTable.sha256 eq meta.sha256) and (FilesTable.user eq meta.userId) }) {
                it[hasThumbnail] = true
            }
        }
    }

    private fun mediaKind(mime: String?, name: String): MediaKind {
        val m = mime?.lowercase()
        if (!m.isNullOrBlank()) {
            return when {
                m.startsWith("image/") -> MediaKind.IMAGE
                m.startsWith("video/") -> MediaKind.VIDEO
                else -> MediaKind.NONE
            }
        }
        return when (name.substringAfterLast('.', "").lowercase()) {
            "jpg", "jpeg", "png", "webp", "gif", "bmp" -> MediaKind.IMAGE
            "mp4", "mov", "webm", "m4v", "3gp", "avi", "mkv" -> MediaKind.VIDEO
            else -> MediaKind.NONE
        }
    }

    /** Bridge for the (non-suspend) generation thread onto the suspend storage API. */
    private fun <T> runBlockingIo(block: suspend () -> T): T = runBlocking(Dispatchers.IO) { block() }
}
